= Lightweight Markup Languages
Writer <duncan.attard.01@um.edu.mt>
v0.9, 04-05-2020 // Star Wars Day ^_^
:appversion: 0.9

:stem: latexmath
:icons: font
:toc:
:toc-placement!:
//:sectnums:



// Github-specific styling.
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

// Shields.
image::https://img.shields.io/badge/license-GPLv3-blue[link="https://www.gnu.org/licenses/gpl-3.0"]
image::https://img.shields.io/badge/version-v0.9-yellow[]

`detectEr` is an inline monitoring tool that synthesised runtime monitors from correctness properties specified in syntactic subset of Hennessy-Milner Logic with recursion that is in its _normal form_ (HML__nf__).
//
`detectEr` assumes access to the source code of the program to be monitored.
//
It instruments monitoring instructions into the target program via _code injection_ by manipulating its parsed abstract syntax tree.
//
The modified syntax tree is compiled by `detectEr` into an executable form which can then be run normally.
//
The instrumented instructions perform the runtime analysis in _synchronous_ fashion as the program executes.
//
Our tool is developed in the Erlang language and for the Erlang eco-system.

toc::[]


== Overview

Correctness properties in `detectEr` are scripted in plain text format using SHML__nf__ syntax.
//
These are then parsed, and the corresponding executable runtime monitor is synthesised in its source or binary form.
//
The resulting file bears the name of the properties script, and contains one function, `mfa_spec`, that encapsulates all the monitoring logic.


=== Script file

More than one property may be specified in a single script file, albeit separated by commas `,`; the last one must be terminated with a period `.`.
//
A specification must target _one_ Erlang function pattern, and may optionally include simple _guard statements_.
//
The guard specification format follows the one used by Erlang, the only difference being that guard functions (_e.g._ `is_pid/1`, `is_alive/1`, _etc._) are currently not supported.
//
Patterns and guards on Erlang binaries, bitstrings and maps will be implemented in future releases.
//
Specifications can only target function calls, _i.e._, `Mod:Fun(Args)`, that have been exported from Erlang modules and invoked via `erlang:spawn/3` or `erlang:spawn/4`.

.{zwsp}
====
The function `test` in module `example` takes two parameters, `A` and `B`, where `A` is an integer in the closed interval [0, 10].
//
A property specification that targets the function `test` is specified as follows:

----
with
  example:test(A, B) when A >= 0, A =< 10
monitor
  <property in SHMLnf>.
----
====

The property itself, `<property in SHMLnf>', is written using the grammar defined next.


=== The SHML__nf__ grammar

The SHML__nf__ grammar is defined by the following BNF:

----
<SHMLnf> ::= ff (falsity, an atom) // <1>
          | X (recursion variable specified as a standard Erlang variable)
          | max(X. <SHMLnf>) (maximal fix-point to specify recursive loops,
          comprised of one variable and a sub-formula
          <SHMLnf>)
          | and(<SHMLnf list>) (a sequence of comma-separated conjuncts where
each is itself a sub-formula <SHML> that however
must start with a necessity [<ACTION>]<SHML>)
----
<1> Falsity, an atom
<2> Recursion variable specified as a standard Erlang variable


== Example













== Stuff
.Possible DefOps manual locations
* West wood maze
** Maze heart
*** Reflection pool
** Secret exit
* Untracked file in git repository


. Protons
. Electrons
. Neutrons


CPU:: The brain of the computer.
Hard drive:: Permanent storage for operating system and/or user files.
RAM:: Temporarily stores information the CPU uses during operation.
Keyboard:: Used to enter text or control items on the screen.
Mouse:: Used to point to and select items on your computer screen.
Monitor:: Displays information in visual form using text and graphics.


[horizontal]
CPU:: The brain of the computer.
Hard drive:: Permanent storage for operating system and/or user files.
RAM:: Temporarily stores information the CPU uses during operation.


* The header in AsciiDoc must start with a document title.
+
The header is optional.


----
This is an example of a _listing block_.
The content inside is displayed as <pre> text.
----

====
Example
====

____
Verse
____

****
Sidebar
****

[cols=2*,options=header]
|===
|Name |Group

|Firefox |Web Browser

|Ruby |Programming Language
|===


stem:[\sqrt4 = 2]

Water (stem:[H_2O]) is a critical component.

stem:[\langle \mu\rangle]


[TIP]

Duncan